name: Build and Deploy FE

on:
  push:
    branches:
      - main # chỉ chạy khi push lên nhánh main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./FE

      - name: Build project
        run: npm run build
        working-directory: ./FE

      - name: Deploy to branch
        run: |
          rm -rf .git
          mkdir deploy_FE
          # copy nguyên dist folder
          cp -r FE/dist deploy_FE/
          # copy Dockerfile và nginx.conf
          cp FE/Dockerfile deploy_FE/
          cp FE/nginx.conf deploy_FE/

          cd deploy_FE
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy FE"
          git branch -M deploy_FE
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin deploy_FE
